version: '3.7'
services:
 postgres:
   image: postgres:latest
   ports:
     - '5432:5432'
   volumes:
     - ./data:/var/lib/postgresql/data

   environment:
     POSTGRES_DB: postgres
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: example
     USER: postgres
