version: '3.7'
services:
 db:
   image: postgres:latest
   ports:
     - '5432:5432'
   volumes:
     -  ./data:/var/lib/postgres

   environment:
     - POSTGRES_DB=app
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=example
# adminer:
#     image: adminer
#     ports:
#       - '8080:8080'